- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/cache/TimeCache.java
- arex-agent-core/src/main/java/io/arex/agent/instrumentation/InstrumentationInstaller.java
- arex-agent/pom.xml
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/api/MethodInstrumentation.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/listener/CaseEvent.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/listener/CaseInitializer.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/listener/CaseListener.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/listener/CaseListenerImpl.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/Constants.java
- arex-instrumentation/pom.xml
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
- arex-instrumentation/time-machine/arex-time-machine/pom.xml
- arex-instrumentation/time-machine/arex-time-machine/src/main/java/io/arex/inst/time/TimeMachineInstrumentation.java
- arex-instrumentation/time-machine/arex-time-machine/src/main/java/io/arex/inst/time/TimeMachineInterceptor.java
- arex-instrumentation/time-machine/arex-time-machine/src/main/java/io/arex/inst/time/TimeMachineModuleInstrumentation.java
current time record and replay
> feat: support time-machine

- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
- arex-instrumentation-foundation/test/java/io/arex/foundation/config/ConfigManagerTest.java
- arex-instrumentation-foundation/test/resources/arex.agent.conf
- pom.xml
> fix: read config #24

- arex-agent/pom.xml
- arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/ApiHandler.java
- arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/DebugHandler.java
- arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/ReplayHandler.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/internal/CallDepth.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/listener/CaseEvent.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/Constants.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/ServiceEntranceMocker.java
- arex-instrumentation/netty/arex-netty-v4/pom.xml
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/ChannelPipelineInstrumentation.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/NettyModuleInstrumentation.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/common/AttributeKey.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/common/NettyHelper.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/RequestTracingHandler.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/ResponseTracingHandler.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/ServerCodecTracingHandler.java
- arex-instrumentation/pom.xml
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletConstants.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
> feat: support netty server

- arex-agent/src/main/java/io/arex/agent/ArexJavaAgent.java
- arex-cli-parent/arex-storage-extension/src/main/java/io/arex/cli/storage/H2StorageService.java
- arex-cli-parent/arex-storage-extension/src/test/java/io/arex/cli/storage/H2StorageServiceTest.java
- arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java
- arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassModuleInstrumentationTest.java
- arex-instrumentation/internal/arex-loader/src/main/java/io/arex/inst/loader/InjectClassInstrumentation.java
- arex-integration-tests/arex-common-integration-test/pom.xml
- arex-integration-tests/arex-common-integration-test/src/test/java/io/arex/integrationtest/common/AbstractIT.java
- arex-integration-tests/arex-dynamic-integration-test/pom.xml
- arex-integration-tests/arex-dynamic-integration-test/src/test/java/io/arex/integrationtest/dynamic/DynamicClassIT.java
- arex-integration-tests/arex-jedis-v4-integration-test/pom.xml
- arex-integration-tests/arex-jedis-v4-integration-test/src/test/java/io/arex/integrationtest/redis/jedis4/Jedis4IT.java
- arex-integration-tests/arex-main-integration-test/pom.xml
- arex-integration-tests/arex-main-integration-test/src/main/java/io/arex/integrationtest/mainapp/MainApp.java
- arex-integration-tests/arex-main-integration-test/src/test/java/io/arex/integrationtest/mainapp/MainAppIT.java
- arex-integration-tests/pom.xml
- pom.xml
integration test not executed after submission by default. because it takes a long time to pull the image of the middleware when docker container is used
> feat: add integration test

- arex-instrumentation/httpclient/arex-httpclient-common/src/test/java/io/arex/inst/httpclient/common/HttpClientExtractorTest.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/pom.xml
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallbackWrapper.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallInstrumentationTest.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallbackWrapperTest.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpClientAdapterTest.java
- arex-instrumentation/pom.xml
- pom.xml
> add okhttp3 ut

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
- arex-instrumentation/database/arex-database-common/src/test/java/io/arex/inst/database/common/DatabaseHelperTest.java
- arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/AbstractEntityPersisterInstrumentation.java
- arex-instrumentation/database/arex-database-hibernate/src/test/java/io/arex/inst/database/hibernate/AbstractEntityPersisterInstrumentationTest.java
1. support hibernate delete mock
2. TypeUtil.getName remove objectArrayToString
> feat: support hibernate delete mock

- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
fix issue #51
support:
// status=302
`return "redirect:/owners/1";`
`response.sendRedirect("/owners/1");`
`return new ModelAndView("redirect:/owners/1");`
`return new RedirectView("/owners/1");`
> fix: record redirect in spring application (#51)

- arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/JacksonSerializer.java
- arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassExtractor.java
- arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java
- arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/listener/DirectExecutor.java
- arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/listener/ResponseConsumer.java
- arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/listener/ResponseFutureCallback.java
- arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassExtractorTest.java
- arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java
1、support dynamic future
2、dynamic operationKey save in enter
> feat: support dynamic result returning future

- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/FutureCallbackWrapper.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientHelper.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentationTest.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentationTest.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallbackWrapper.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallInstrumentationTest.java
- arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpCallbackWrapperTest.java
- arex-instrumentation/httpclient/arex-httpclient-webclient-v5/src/main/java/io/arex/inst/httpclient/webclient/v5/WebClientInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-webclient-v5/src/test/java/io/arex/inst/httpclient/webclient/v5/WebClientInstrumentationTest.java
1. apache http client sync/async call √
2. okhttp sync/async call √
3. webclient async call √
> feat: ignore httpclient request which no need record

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/ArexMocker.java
- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/Mocker.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/Config.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/ConfigBuilder.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/MockUtils.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigConstants.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
add record version(record case & load config)
> feat: add record version

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Add issue templates: bug_report, feature_request
> docs: create github issue templates

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/StringUtil.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/StringUtilTest.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
- arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
1. support generic type. ex: `Single<T>, Double<T, E>`
2. support nested types. ex: `List<Map<K, V>>`, `Map<K, List<T>>`,  `Map<K, Map<K1, V1>>`....
> feat: support generics and nested types

- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/FutureCallbackWrapperTest.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapterTest.java
> fix: apache http client class cast error

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/AgentClassLoader.java
- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/AgentInitializer.java
- arex-agent-core/src/main/java/io/arex/agent/instrumentation/InstrumentationInstaller.java
- arex-instrumentation-foundation/pom.xml
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/AgentStatusEnum.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigQueryRequest.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigQueryResponse.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
- arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
- arex-instrumentation-foundation/src/test/java/io/arex/foundation/healthy/HealthManagerTest.java
- arex-instrumentation-foundation/src/test/java/io/arex/foundation/services/ConfigServiceTest.java
1. Add fields: `agentStatus/systemProperties/systemEnv` to `ConfigQueryRequest`
2. Load agent config error more `maxRetry`: 3 times in a row, then change `period*10` : 20min
> fix: optimize load agent config

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/internal/WeakCache.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/internal/WeakCacheTest.java
> fix: NPE by WeakCache put null value

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
- arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletExtractorTest.java
Create the Mock object based on the mocker identifier passed in
> feat: create the mock based on request

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/Config.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/IgnoreUtils.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/config/ConfigTest.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/IgnoreUtilsTest.java
> fix: ignore path with start and end wildcard

- arex-agent/pom.xml
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/pom.xml
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/main/java/io/arex/inst/httpclient/resttemplate/ResponseEntityWrapper.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/main/java/io/arex/inst/httpclient/resttemplate/RestTemplateExtractor.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/main/java/io/arex/inst/httpclient/resttemplate/RestTemplateInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/main/java/io/arex/inst/httpclient/resttemplate/RestTemplateModuleInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/test/java/io/arex/inst/httpclient/resttemplate/ResponseEntityWrapperTest.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/test/java/io/arex/inst/httpclient/resttemplate/RestTemplateExtractorTest.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/test/java/io/arex/inst/httpclient/resttemplate/RestTemplateInstrumentationTest.java
- arex-instrumentation/httpclient/arex-httpclient-resttemplate/src/test/java/io/arex/inst/httpclient/resttemplate/RestTemplateModuleInstrumentationTest.java
- arex-instrumentation/pom.xml
> feat: support spring restTemplate

- README.md
- arex-instrumentation/authentication/arex-jwt/pom.xml
- arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/AuthOJWTInstrumentation.java
- arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/JJWTGenerator.java
- arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/JJWTInstrumentation.java
- arex-instrumentation/authentication/arex-jwt/src/main/java/io/arex/inst/authentication/jwt/JWTModuleInstrumentation.java
- arex-instrumentation/authentication/arex-jwt/src/test/java/io/arex/inst/authentication/jwt/AuthOJWTInstrumentationTest.java
- arex-instrumentation/authentication/arex-jwt/src/test/java/io/arex/inst/authentication/jwt/JJWTGeneratorTest.java
- arex-instrumentation/authentication/arex-jwt/src/test/java/io/arex/inst/authentication/jwt/JJWTInstrumentationTest.java
- arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloConfigHelper.java
- pom.xml
> feat: support jjwt mock

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/constants/ConfigConstants.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/Config.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/config/ConfigTest.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/config/ConfigManager.java
- arex-instrumentation-foundation/src/test/java/io/arex/foundation/config/ConfigManagerTest.java
Fix #229 
Support disable record by set property: `-Darex.disable.record=true`
> feat: support disbale record by config

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/StringUtil.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/StringUtilTest.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboConsumerExtractor.java
Fix #237 
filter out effective raw generic in collection for deserialize: 
```
class A<T> {
List<T> t;
}
A<List<T>> -> A<T>
```
> fix: nest generic

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/cache/LoadedModuleCache.java
- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/ComparableVersion.java
- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/StringUtil.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/cache/LoadedModuleCacheTest.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/model/ComparableVersionTest.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/StringUtilTest.java
- arex-instrumentation-api/src/main/java/io/arex/inst/extension/ModuleDescription.java
- arex-instrumentation-api/src/main/java/io/arex/inst/extension/matcher/ModuleVersionMatcher.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ResourceManager.java
- arex-instrumentation-api/src/test/java/io/arex/inst/extension/ModuleDescriptionTest.java
- arex-instrumentation-api/src/test/java/io/arex/inst/extension/matcher/ModuleVersionMatcherTest.java
- arex-instrumentation/database/arex-database-hibernate/src/main/java/io/arex/inst/database/hibernate/HibernateModuleInstrumentation.java
- arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/MyBatisModuleInstrumentation.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboModuleInstrumentation.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboModuleInstrumentation.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/NettyModuleInstrumentation.java
- arex-instrumentation/redis/arex-jedis-v2/src/main/java/io/arex/inst/jedis/v2/JedisModuleInstrumentation.java
- arex-instrumentation/redis/arex-jedis-v4/src/main/java/io/arex/inst/jedis/v4/JedisModuleInstrumentation.java
- arex-instrumentation/redis/arex-lettuce-v5/src/main/java/io/arex/inst/lettuce/v5/LettuceModuleInstrumentation.java
- arex-instrumentation/redis/arex-lettuce-v6/src/main/java/io/arex/inst/lettuce/v6/LettuceModuleInstrumentation.java
- arex-instrumentation/redis/arex-redission-v3/src/main/java/io/arex/inst/redisson/v3/RedissonModuleInstrumentation.java
before: current: 1.2 target: 0.9 , current Version < target Version
after: current Version > target Version
> fix: module version match error

- .github/workflows/build.yml
- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/ParameterizedTypeImpl.java
- arex-attacher/pom.xml
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
- arex-instrumentation-foundation/pom.xml
- arex-instrumentation/dynamic/arex-cache/pom.xml
- arex-instrumentation/dynamic/arex-dynamic/pom.xml
- arex-instrumentation/pom.xml
- pom.xml
> feat: support JDK 17

- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java
> fix: set servlet request charset utf-8

- README.md
- arex-agent/pom.xml
- pom.xml
> build: changing packaging based on active profile in pom

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/ReflectUtil.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/ReflectUtilTest.java
- arex-instrumentation-api/pom.xml
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/serializer/Serializer.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/listener/EventProcessorTest.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/serializer/SerializerTest.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
- arex-instrumentation-foundation/pom.xml
- arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
- arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
- pom.xml
> fix: parsing failed for Collection<Collection<T>>

- arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
- arex-agent-core/src/main/java/io/arex/agent/instrumentation/InstrumentationInstaller.java
https://github.com/raphw/byte-buddy/issues/1441
> fix: forkJoinTask trace loss

- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/FutureCallbackWrapper.java
> fix: NPE caused by apache asynchttpclient callback being null

- arex-agent/pom.xml
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/serializer/StringSerializable.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/GsonSerializer.java
- arex-instrumentation-foundation/src/main/java/io/arex/foundation/serializer/JacksonSerializer.java
- arex-instrumentation-foundation/src/test/java/io/arex/foundation/serializer/GsonSerializerTest.java
- arex-instrumentation/database/arex-database-common/src/main/java/io/arex/inst/database/common/DatabaseExtractor.java
- arex-instrumentation/database/arex-database-mongo/pom.xml
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/AggregateInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/ListIndexesInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/MongoHelper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/MongoModuleInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/ReadOperationInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/ResourceManagerInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/WriteOperationInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/BulkWriteResultWrapper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/DeleteResultWrapper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/InsertManyResultWrapper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/InsertOneResultWrapper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/ResultWrapper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/wrapper/UpdateResultWrapper.java
- arex-instrumentation/database/arex-database-mongo/src/test/java/io/arex/inst/database/mongo/MongoHelperTest.java
- arex-instrumentation/pom.xml
> feat: support mongo

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/IgnoreUtils.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/IgnoreUtilsTest.java
- pom.xml
feat: add log when blocklist is hit during replay
> feat: add log when blocklist is hit during replay

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java
- arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboAdapter.java
- arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboAdapter.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboAdapter.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboProviderExtractor.java
> fix: dubbo record original request

- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java
- arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java
- arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5Test.java
fix: inconsistency of paths in the configuration list
> fix:inconsistency of paths in the configuration list

- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
> fix: pattern match error

- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyRequestWrapperV3.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyRequestWrapperV5.java
> fix: request body is null when request content type is form-data

- arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroAuthorSecurityManagerInstrumentation.java
- arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroAuthorizingAnnotationInstrumentation.java
- arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroDelegatingSubjectInstrumentation.java
- arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroModuleInstrumentation.java
- arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroPathMatchingFilterInstrumentation.java
- arex-instrumentation/authentication/arex-shiro/src/test/java/io/arex/inst/authentication/shiro/ShiroAuthorSecurityManagerInstrumentationTest.java
- arex-instrumentation/authentication/arex-shiro/src/test/java/io/arex/inst/authentication/shiro/ShiroAuthorizingAnnotationInstrumentationTest.java
- arex-instrumentation/authentication/arex-shiro/src/test/java/io/arex/inst/authentication/shiro/ShiroDelegatingSubjectInstrumentationTest.java
- arex-instrumentation/authentication/arex-shiro/src/test/java/io/arex/inst/authentication/shiro/ShiroModuleInstrumentationTest.java
- arex-instrumentation/authentication/arex-shiro/src/test/java/io/arex/inst/authentication/shiro/ShiroPathMatchingFilterInstrumentationTest.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
- arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java
> fix: exclude pre-request in http method

- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/InvocableHandlerInstrumentationV3.java
- arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java
> fix: below sping-core-4.3.0-RELEASE record error

- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/ApacheHttpClientModuleInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/async/RequestProducerInstrumentation.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentationTest.java
- arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/RequestProducerInstrumentationTest.java
- pom.xml
> feat: support es java client

- arex-agent/pom.xml
- arex-instrumentation/pom.xml
- arex-instrumentation/redis/arex-jedis-v2/src/main/java/io/arex/inst/jedis/v2/JedisWrapper.java
- arex-instrumentation/redis/arex-jedis-v4/src/main/java/io/arex/inst/jedis/v4/JedisWrapper.java
- arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/RedisKeyUtil.java
- arex-instrumentation/redis/arex-redis-common/src/main/java/io/arex/inst/redis/common/lettuce/wrapper/RedisCommandWrapper.java
- arex-instrumentation/redis/arex-redis-common/src/test/java/io/arex/inst/redis/common/RedisKeyUtilTest.java
- arex-instrumentation/redis/arex-redission-v3/src/main/java/io/arex/inst/redisson/v3/RedissonWrapperCommon.java
- arex-instrumentation/redis/arex-redission-v3/src/test/java/io/arex/inst/redisson/v3/RedissonWrapperCommonTest.java
- arex-instrumentation/redis/arex-spring-data-redis/pom.xml
- arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/MethodCollector.java
- arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/RedisTemplateProvider.java
- arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/SpringDataRedisInstrumentation.java
- arex-instrumentation/redis/arex-spring-data-redis/src/main/java/io/arex/inst/spring/data/redis/SpringDataRedisModuleInstrumentation.java
- arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/MethodCollectorTest.java
- arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/RedisTemplateProviderTest.java
- arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/SpringDataRedisInstrumentationTest.java
- arex-instrumentation/redis/arex-spring-data-redis/src/test/java/io/arex/inst/spring/data/redis/SpringDataRedisModuleInstrumentationTest.java
> feat: supports the redisTemplate component provided by spring data redis

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/request/RequestHandlerManager.java
- arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloConfigChecker.java
- arex-instrumentation/dubbo/arex-dubbo-alibaba/pom.xml
- arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboAdapter.java
- arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboConsumerExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-alibaba/src/test/java/io/arex/inst/dubbo/alibaba/DubboAdapterTest.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboAdapter.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboConsumerExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/test/java/io/arex/inst/dubbo/apache/v2/DubboAdapterTest.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboAdapter.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboConsumerExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/test/java/io/arex/inst/dubbo/apache/v3/DubboAdapterTest.java
- arex-instrumentation/dubbo/arex-dubbo-common/src/main/java/io/arex/inst/dubbo/common/DubboConstants.java
> feat: optimize dubbo generic invoke record and replay

- arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
- arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
> fix: normalize className enhanced by cglib

- arex-instrumentation/dynamic/arex-dynamic-common/pom.xml
- arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
- arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
> feat: ProceedingJoinPoint args request type

- arex-instrumentation/database/arex-database-common/src/main/java/io/arex/inst/database/common/DatabaseExtractor.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/MongoHelper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/WriteOperationInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/test/java/io/arex/inst/database/mongo/MongoHelperTest.java
> feat: mongo key holder

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/ArrayUtils.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/ArrayUtilsTest.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/TypeUtil.java
- arex-instrumentation-api/src/test/java/io/arex/inst/runtime/util/TypeUtilTest.java
- arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java
Fix https://github.com/arextest/arex-agent-java/issues/481
> fix: ArrayUtils.toString NPE caused by null array element

- arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/InternalExecutor.java
- arex-instrumentation/database/arex-database-mybatis3/src/test/java/io/arex/inst/database/mybatis3/InternalExecutorTest.java
> fix: mybatis non-standard key properties

- arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/InternalExecutor.java
- arex-instrumentation/database/arex-database-mybatis3/src/test/java/io/arex/inst/database/mybatis3/InternalExecutorTest.java
> feat: support mybatis plus insertBatchSomeColumn primary key

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ArexContext.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/MongoHelper.java
- arex-instrumentation/database/arex-database-mongo/src/main/java/io/arex/inst/database/mongo/QueryBatchCursorInstrumentation.java
- arex-instrumentation/database/arex-database-mongo/src/test/java/io/arex/inst/database/mongo/MongoHelperTest.java
- pom.xml
> feat: support mongo get more

- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboProviderExtractor.java
> fix: add response attachments on service enter

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/ctx/RunnableWrapper.java
- arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/ctx/RunnableWrapperTest.java
> feat: support comparable runnable

- arex-instrumentation-api/src/main/java/io/arex/inst/extension/ModuleDescription.java
- arex-instrumentation-api/src/main/java/io/arex/inst/extension/matcher/ModuleVersionMatcher.java
- arex-instrumentation-api/src/test/java/io/arex/inst/extension/ModuleDescriptionTest.java
- arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/InternalExecutor.java
- arex-instrumentation/database/arex-database-mybatis3/src/main/java/io/arex/inst/database/mybatis3/MyBatisModuleInstrumentation.java
> feat: support multiModuleNames and compatible mybatis version < 3.3.0

- arex-instrumentation/redis/arex-lettuce-v5/src/main/java/io/arex/inst/lettuce/v5/LettuceModuleInstrumentation.java
- arex-instrumentation/redis/arex-lettuce-v6/src/main/java/io/arex/inst/lettuce/v6/LettuceModuleInstrumentation.java
> fix: project start fail while lettuce version between 6.0 - 6.1

- arex-instrumentation/redis/arex-redission-v3/src/main/java/io/arex/inst/redisson/v3/RedissonInstrumentation.java
fix https://github.com/arextest/arex-agent-java/issues/530
> fix getBucketWithCodecAdvice

- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
fix https://github.com/arextest/arex-agent-java/issues/538
> fix: no such method at `HttpMethod.HEAD.matches`

- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/RecordLimiter.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
fix https://github.com/arextest/arex-agent-java/issues/551
> fix: NoClassDefFoundError: org/springframework/http/HttpMethod

- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/NettyModuleInstrumentation.java
> fix: HttpRequestDecoder NoClassDefFoundError

- arex-instrumentation/redis/arex-redission-v3/src/main/java/io/arex/inst/redisson/v3/RedissonInstrumentation.java
对 issue 的修复 PR https://github.com/arextest/arex-agent-java/issues/603
> fix: Redisson getBucket(String, Codec) bug fix

- arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/MockResult.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ArexContext.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/EventProcessor.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/EventSource.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java
- arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/IgnoreUtils.java
- arex-instrumentation/dubbo/arex-dubbo-alibaba/src/main/java/io/arex/inst/dubbo/alibaba/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v2/src/main/java/io/arex/inst/dubbo/apache/v2/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-apache-v3/src/main/java/io/arex/inst/dubbo/apache/v3/DubboProviderExtractor.java
- arex-instrumentation/dubbo/arex-dubbo-common/src/main/java/io/arex/inst/dubbo/common/AbstractAdapter.java
- arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java
- arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java
- arex-instrumentation/netty/arex-netty-v3/src/main/java/io/arex/inst/netty/v3/server/RequestTracingHandler.java
- arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/RequestTracingHandler.java
- arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java
1.merge commit for customized.
> feat: add record in replay
