arextest/arex-agent-java

arex-cli-parent/arex-server-extension/src/main/java/io/arex/cli/server/handler/ApiHandler.java, arex-cli-parent/arex-server-extension/src/test/java/io/arex/cli/server/handler/DebugHandlerTest.java, arex-cli-parent/arex-server-extension/src/test/java/io/arex/cli/server/handler/ReplayHandlerTest.java, arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/MockerCategory.java, arex-instrumentation-foundation/src/main/java/io/arex/foundation/model/ServiceEntranceMocker.java, arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/RequestTracingHandler.java, arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/ResponseTracingHandler.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java
MongoDB uses the dot notation to access the elements of an array and to access the fields of an embedded document.
https://www.mongodb.com/docs/manual/core/document/#dot-notation
=> fix: change servlet headers type to string

arex-instrumentation/httpclient/arex-httpclient-common/src/main/java/io/arex/inst/httpclient/common/HttpResponseWrapper.java
When starting with Tomcat, `StringTuple` is loaded by ParallelWebappClassLoader, `JacksonSerializer` is loaded by AppClassLoader, so `@JsonProperty("f")` is invalid, I gonna fix with this temporary solution.
=> fix: httpclient header serialization

arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/MockCategoryType.java, arex-agent/pom.xml, arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/MockUtils.java, arex-instrumentation/dubbo/arex-dubbo/pom.xml, arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboAdapter.java, arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboConsumerExtractor.java, arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboConsumerInstrumentation.java, arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboModuleInstrumentation.java, arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboProviderExtractor.java, arex-instrumentation/dubbo/arex-dubbo/src/main/java/io/arex/inst/dubbo/DubboProviderInstrumentation.java, arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboAdapterTest.java, arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboConsumerExtractorTest.java, arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboConsumerInstrumentationTest.java, arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboModuleInstrumentationTest.java, arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboProviderExtractorTest.java, arex-instrumentation/dubbo/arex-dubbo/src/test/java/io/arex/inst/dubbo/DubboProviderInstrumentationTest.java, arex-instrumentation/netty/arex-netty-v4/src/main/java/io/arex/inst/netty/v4/server/RequestTracingHandler.java, arex-instrumentation/netty/arex-netty-v4/src/test/java/io/arex/inst/netty/v4/server/RequestTracingHandlerTest.java, arex-instrumentation/pom.xml, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java
=> feat: support dubbo 3.x

arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/ServletAdapter.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java
FUll URL example: `http://localhost:8080/commutity/httpClientTest/okHttp?k1=v1&k2=v2`
The URL required for replay is `/commutity/httpClientTest/okHttp?k1=v1&k2=v2`, need to contain `queryString`
request.getContextPath() -> /commutity
request.getServletPath() -> /httpClientTest/okHttp
request.getRequestURI() -> /commutity/httpClientTest/okHttp
request.getQueryString() -> k1=v1&k2=v2
=> fix: record servlet request full url

arex-instrumentation/internal/arex-executors/src/main/java/io/arex/inst/executors/ThreadPoolInstrumentation.java, arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ExecutorsModuleInstrumentationTest.java, arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ForkJoinTaskInstrumentationTest.java, arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/FutureTaskInstrumentationTest.java, arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ThreadInstrumentationTest.java, arex-instrumentation/internal/arex-executors/src/test/java/io/arex/inst/executors/ThreadPoolInstrumentationTest.java
Support ForkJoinPool missing retransformed methods:
```java
java.util.concurrent.ForkJoinPool#execute(java.lang.Runnable)
java.util.concurrent.ForkJoinPool#submit(java.lang.Runnable, T)
java.util.concurrent.ForkJoinPool#submit(java.lang.Runnable)
java.util.concurrent.ForkJoinPool#submit(java.util.concurrent.Callable<T>)
```
=> fix: add ForkJoinPool class to executros

README.md, arex-agent/pom.xml, arex-instrumentation/authentication/arex-shiro/pom.xml, arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroInstrumentation.java, arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroModuleInstrumentation.java, arex-instrumentation/authentication/arex-shiro/src/test/java/io/arex/inst/authentication/shiro/ShiroInstrumentationTest.java, arex-instrumentation/authentication/arex-shiro/src/test/java/io/arex/inst/authentication/shiro/ShiroModuleInstrumentationTest.java, arex-instrumentation/pom.xml
=> feat: support apache shiro

arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapter.java, arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientHelper.java, arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/main/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentation.java, arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/async/InternalHttpAsyncClientInstrumentationTest.java, arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/common/ApacheHttpClientAdapterTest.java, arex-instrumentation/httpclient/arex-httpclient-apache-v4/src/test/java/io/arex/inst/httpclient/apache/sync/InternalHttpClientInstrumentationTest.java, arex-instrumentation/httpclient/arex-httpclient-common/src/main/java/io/arex/inst/httpclient/common/HttpClientAdapter.java, arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/main/java/io/arex/inst/httpclient/okhttp/v3/OkHttpClientAdapter.java, arex-instrumentation/httpclient/arex-httpclient-okhttp-v3/src/test/java/io/arex/inst/httpclient/okhttp/v3/OkHttpClientAdapterTest.java
```text
failed: java.lang.UnsupportedOperationException
at org.apache.http.client.entity.GzipCompressingEntity.getContent(GzipCompressingEntity.java:100)
at org.apache.http.util.EntityUtils.toByteArray(EntityUtils.java:122)
at io.arex.inst.httpclient.apache.common.ApacheHttpClientAdapter.getRequestBytes(ApacheHttpClientAdapter.java:52)
at io.arex.inst.httpclient.common.HttpClientExtractor.encodeRequest(HttpClientExtractor.java:82)
at io.arex.inst.httpclient.common.HttpClientExtractor.makeMocker(HttpClientExtractor.java:76)
at io.arex.inst.httpclient.common.HttpClientExtractor.record(HttpClientExtractor.java:40)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
at …
```
=> fix: get request bytes from GzipCompressingEntity

arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java, arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/DynamicClassEntity.java, arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java, arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/ReplaceMethodHelper.java, arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java, arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/ReplaceMethodClass.java, arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/ReplaceMethodHelperTest.java
The use of uuid/nextInt exists in the application code and has an impact on the subsequent logic.
If the mock `UUID.randomUUID()/Random.nextInt()` method cannot control the modification range,
it is easy to record a large amount of useless data. 
Therefore, the `UUID.randomUUID()/Random.nextInt()`  in the method configured by the user 
is searched for using logic and replaced, so as to achieve the effect of recording the uuid 
in the specified method.
ex: UUID Demo :
```java
package com.ctrip.flight.test.service;
public class TestService {
public void testDemo(String s) {
...
String transId = UUID.randomUUID().toString();
...
}
}
```
Dynamic class configuration:
FullClassName : com.ctrip.flight.test.service.TestService
MethodName : testDemo
ParameterTypes : java.lang.String
keyFormula : …
=> feat: support Random#nextInt mock and support UUID/currentTime in constructor

README.md, arex-agent/pom.xml, arex-instrumentation/authentication/arex-jcasbin/pom.xml, arex-instrumentation/authentication/arex-jcasbin/src/main/java/io/arex/inst/authentication/jcasbin/JCasbinInstrumentation.java, arex-instrumentation/authentication/arex-jcasbin/src/main/java/io/arex/inst/authentication/jcasbin/JCasbinModuleInstrumentation.java, arex-instrumentation/authentication/arex-jcasbin/src/test/java/io/arex/inst/authentication/jcasbin/JCasbinInstrumentationTest.java, arex-instrumentation/authentication/arex-jcasbin/src/test/java/io/arex/inst/authentication/jcasbin/JCasbinModuleInstrumentationTest.java, arex-instrumentation/authentication/arex-shiro/src/main/java/io/arex/inst/authentication/shiro/ShiroInstrumentation.java, arex-instrumentation/authentication/arex-spring-security/pom.xml, arex-instrumentation/authentication/arex-spring-security/src/main/java/io/arex/inst/authentication/springsecurity/SpringSecurityInstrumentation.java, arex-instrumentation/authentication/arex-spring-security/src/test/java/io/arex/inst/authentication/springsecurity/SpringSecurityInstrumentationTest.java, arex-instrumentation/pom.xml, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/ServletAdapter.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV5.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/FilterModuleInstrumentationV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/FilterModuleInstrumentationV5.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/inst/ServletInstrumentationV5.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5Test.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV3Test.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/FilterInstrumentationV5Test.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/FilterModuleInstrumentationV3Test.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/inst/FilterModuleInstrumentationV5Test.java
=> feat: support jcasbin

arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java, arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/AbstractDynamicTestClass.java, arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java, arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicTestClass.java
Support for dynamic class config using wildcards and abstract class
- infix: `io.arex.inst.dynamic.*namicTest*`
- suffix: `io.arex.inst.dynamic.*namicTestClass`
- prefix: `io.arex.inst.dynamic.DynamicTest*`
- equals: `io.arex.inst.dynamic.DynamicTestClass`
- abstract class or interface: `ac:io.arex.inst.dynamic.AbstractDynamicTestClass`
=> feat: support for dynamic class config using wildcards and abstract class

arex-agent/pom.xml, arex-instrumentation/dynamic/arex-dynamic-common/pom.xml, arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/DynamicClassExtractor.java, arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/listener/DirectExecutor.java, arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/listener/ListenableFutureAdapter.java, arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/listener/ResponseConsumer.java, arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/DynamicClassExtractorTest.java, arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/DynamicClassInstrumentation.java, arex-instrumentation/dynamic/arex-dynamic/src/main/java/io/arex/inst/dynamic/ReplaceMethodHelper.java, arex-instrumentation/dynamic/arex-dynamic/src/test/java/io/arex/inst/dynamic/DynamicClassInstrumentationTest.java, arex-instrumentation/dynamic/arex-spring-cache/pom.xml, arex-instrumentation/dynamic/arex-spring-cache/src/main/java/io/arex/inst/spring/SpringCacheAdviceHelper.java, arex-instrumentation/dynamic/arex-spring-cache/src/main/java/io/arex/inst/spring/SpringCacheInstrumentation.java, arex-instrumentation/dynamic/arex-spring-cache/src/main/java/io/arex/inst/spring/SpringCacheModuleInstrumentation.java, arex-instrumentation/dynamic/arex-spring-cache/src/test/java/io/arex/inst/spring/SpringCacheAdviceHelperTest.java, arex-instrumentation/dynamic/arex-spring-cache/src/test/java/io/arex/inst/spring/SpringCacheInstrumentationTest.java, arex-instrumentation/dynamic/arex-spring-cache/src/test/java/io/arex/inst/spring/SpringCacheModuleInstrumentationTest.java, arex-instrumentation/pom.xml
Demo:
`@Cacheable(value = "myCache")`
public Mealrecomrestaurant queryByPk(Number id)
throws SQLException {
return queryByPk(id, null);
}
FullclassName：com.ctrip.flight.arex.dao.MealrecomRestaurantDao
methodName: queryByPk
parameterType: java.lang.Number
=> feat: support spring cache mock

arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/model/Mocker.java, arex-agent-core/src/test/java/io/arex/agent/instrumentation/InstrumentationInstallerTest.java, arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ArexContext.java, arex-instrumentation-api/src/main/java/io/arex/inst/runtime/context/ContextManager.java, arex-instrumentation-api/src/main/java/io/arex/inst/runtime/model/ArexConstants.java, arex-instrumentation-api/src/main/java/io/arex/inst/runtime/util/MockUtils.java, arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/DataCollectorService.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletExtractor.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletUtil.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/ServletAdapter.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyResponseWrapperV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/wrapper/CachedBodyResponseWrapperV5.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletAdviceHelperTest.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletExtractorTest.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/ServletUtilTest.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5Test.java, pom.xml
Fix: #51 
1. Store the original url to context when response returns 302
2. Change `sendRedirect` method to pass `arex-record-id` of the original request
3. Save recorded data base on request type: redirect or not
=> fix: record servlet request redirect

arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java
bytebuddy transform logic:
1. When `builder.installOn(instrumentation)`, get all the classes loaded in the current loader, match according to the defined transformer, and match the classes to form a mapping relationship: `className -> Instrumentation`.
2. When the class that is not loaded `after builder.installOn(instrumentation)` is completed is loaded, it will be matched by calling the classLoader transformer through classLoader defineClass, and the matched class will be modified.
However, when the agent `builder.installOn(instrumentation)` obtained the config configuration through `io.arex.foundation.util.AsyncHttpClientUtil` before, 
the use of `new CompletableFuture<>()` caused the ForkJoinTask class to be loaded, but the innerClass did not (ex: …
=> fix: ForkJoinTask inner class not transform

.github/workflows/build.yml
The property 'sonar.login' is deprecated and will be removed in the future. Please use the 'sonar.token' property instead when passing a token.
=> chore: change to sonar.token

arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloConfigHelper.java, arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloDubboRequestHandler.java, arex-instrumentation/config/arex-apollo/src/main/java/io/arex/inst/config/apollo/ApolloServletV3RequestHandler.java, arex-instrumentation/config/arex-apollo/src/test/java/io/arex/inst/config/apollo/ApolloConfigHelperTest.java
If business application not loaded apollo-client.jar, it will log "ClassNoDefFound" exception(doesn't affect normal business logic),
and we will refactor this issue on next version.
=> fix: check apollo loaded

README.md, arex-agent/pom.xml, arex-instrumentation/httpclient/arex-httpclient-common/src/main/java/io/arex/inst/httpclient/common/HttpResponseWrapper.java, arex-instrumentation/httpclient/arex-httpclient-feign/pom.xml, arex-instrumentation/httpclient/arex-httpclient-feign/src/main/java/io/arex/inst/httpclient/feign/FeignClientAdapter.java, arex-instrumentation/httpclient/arex-httpclient-feign/src/main/java/io/arex/inst/httpclient/feign/FeignClientInstrumentation.java, arex-instrumentation/httpclient/arex-httpclient-feign/src/main/java/io/arex/inst/httpclient/feign/FeignClientModuleInstrumentation.java, arex-instrumentation/httpclient/arex-httpclient-feign/src/test/java/io/arex/inst/httpclient/feign/FeignClientAdapterTest.java, arex-instrumentation/httpclient/arex-httpclient-feign/src/test/java/io/arex/inst/httpclient/feign/FeignClientInstrumentationTest.java, arex-instrumentation/httpclient/arex-httpclient-feign/src/test/java/io/arex/inst/httpclient/feign/FeignClientModuleInstrumentationTest.java, arex-instrumentation/pom.xml, pom.xml
=> feat: support feign 

arex-instrumentation/database/arex-database-common/src/main/java/io/arex/inst/database/common/DatabaseHelper.java, arex-instrumentation/database/arex-database-common/src/test/java/io/arex/inst/database/common/DatabaseHelperTest.java
原逻辑只处理了 hql 的命名参数，没有处理位置参数，若查询语句为：
```java
Query query=session.createQuery(“from User user where user.id=?”); 
query.setInteger(0, 410); 
```
则会记录不到参数，直接返回 null：
修改后效果：
=> feat: supports parse positionalParameter in hibernate

arex-instrumentation-api/src/main/java/io/arex/inst/runtime/listener/EventProcessor.java, arex-instrumentation-api/src/main/java/io/arex/inst/runtime/request/RequestHandlerManager.java, arex-instrumentation-api/src/test/java/io/arex/inst/runtime/request/RequestHandlerManagerTest.java
Before jdk9 ForkJoinPool.common() returns an Executor with a ClassLoader of your main Thread, in Java 9 this behave changes , and return an executor with the system jdk system classloader.
https://stackoverflow.com/questions/49113207/completablefuture-forkjoinpool-set-class-loader
=> fix: thread context classloader propagation in forkjoinpool

arex-instrumentation-api/src/main/java/io/arex/inst/runtime/config/listener/SerializeSkipInfoListener.java, arex-instrumentation-foundation/src/main/java/io/arex/foundation/services/ConfigService.java
序列化忽略配置，没有指定字段名时，解析配置时数组越界异常：
查看代码发现没有做判断：
添加数组长度判断即可。
=> fix: buildSkipInfos error when fieldName is empty

arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/ArrayUtils.java, arex-agent-bootstrap/src/main/java/io/arex/agent/bootstrap/util/ReflectUtil.java, arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/ArrayUtilsTest.java, arex-agent-bootstrap/src/test/java/io/arex/agent/bootstrap/util/ReflectUtilTest.java, arex-agent-core/src/main/java/io/arex/agent/instrumentation/BaseAgentInstaller.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/ServletAdviceHelper.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/SpringUtil.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3.java, arex-instrumentation/servlet/arex-httpservlet/src/main/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/SpringUtilTest.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV3Test.java, arex-instrumentation/servlet/arex-httpservlet/src/test/java/io/arex/inst/httpservlet/adapter/impl/ServletAdapterImplV5Test.java
=> feat: support get pattern from Spring requestMappingInfo

arex-instrumentation/dynamic/arex-dynamic-common/src/main/java/io/arex/inst/dynamic/common/ExpressionParseUtil.java, arex-instrumentation/dynamic/arex-dynamic-common/src/test/java/io/arex/inst/dynamic/common/ExpressionParseUtilTest.java
Problem: Root built-in functions, such as # root.mathodName, are not supported, 
such as: Spring @Cache annotation has a key construction exception, recording in empty input parameters:
Fix solution: By constructing a root object, support parsing root functions using spel expressions.
=> feat: add root object
